### ISSUE TITLE
Translate Type declarations into tuple structures.

### ISSUE THREAD

**Issue by ytanimura** [ricosjp/ruststep#130]
In the current implementation, the implementation by TYPE declaration is translated into a type alias. However, the intention is to treat the TYPE declaration in the express language as a separate type rather than a simple type alias. In particular, constraints can be given in the where declaration. Therefore, the TYPE declaration should normally be translated as a tuple structure in Rust code.

**Comment by termoshtt** [comment]
> In particular, constraints can be given in the where declaration. 

We have a lot of things to support `WHERE` clause in ruststep. This issue is one of them.

**Comment by termoshtt** [comment]
From [slack discussion](https://ricosiste.slack.com/archives/C01PWGGDUA0/p1637047377046400), I understand we need to create a table for each `TYPE` definitions:

Let's consider a case of `list_of_reversible_topology_item` in AP203

```
  TYPE reversible_topology_item = SELECT
    (edge,
     path,
     face,
     face_bound,
     closed_shell,
     open_shell);
  END_TYPE; -- reversible_topology_item

  TYPE list_of_reversible_topology_item = LIST [0:?] OF
              reversible_topology_item;
  END_TYPE; -- list_of_reversible_topology_item
```

This will be compiled into Rust code like

```
type ListOfReversibleTopologyItem = Vec<ReversibleToplotyItem>;
```

and **this does not create a table in `Tables`**. This causes following problem:

```
#1 = LIST_OF_REVERSIBLE_TOPOLOTY_ITEM(EDGE((...)), FACE((..)));
```

This input must be acceptable for above EXPRESS schema. But when we deserialize it into `Tables`, it does not has table where we should insert it.

TODO
-------
- [ ] Create tuple struct for each `TYPE` declaration
- [ ] Generate Holder struct for it, support `#[derive(Holder)]` for tuple struct
- [ ] Add table for this `TYPE` declaration
