### ISSUE TITLE
Empty tail remarks turn the following line in to remarks

### ISSUE THREAD

**Issue by g-rauhoeft** [ricosjp/ruststep#71]
While parsing one of the APs I noticed that a line following empty tail remarks is ignored by the parser.

An example would be:
```
--
A
```
In this case A would be treated as a remark. I'm currently working on a fix for this.

**Comment by g-rauhoeft** [comment]
The fix is to replace `multispace0` with `space0` in `tail_remark`.

**Comment by termoshtt** [comment]
Done in #74
